dataset_name: error_dataset
train_split: ['training', 'validation']
val_split: ['test']
dataset: {
  backbone: omnivore,
  division_type: recordings,
  videos_type: 'all',
  json_file: ./annotations/annotations_actionformer.json,
  feat_folder: './data/error_dataset/features/omnivore_swinB_epic',
  file_prefix: ~,
  file_suffix: '_360p',
  file_ext: .npz,
  num_classes: 353,
  input_dim: 1024,
  feat_stride: 30,
  num_frames: 90,
  default_fps: 29.97,
  trunc_thresh: 0.3,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 4096,
}
model: {
  regression_range: [
    [0, 4], 
    [2, 8], 
    [4, 16], 
    [8, 32], 
    [16, 64], 
    [32, 128],
    [64, 256],
    [128, 10000]
  ],
  fpn_type: identity,
  backbone_arch: [2, 2, 7],
  max_buffer_len_factor: 4.0,
  n_mha_win_size: 9,
  use_abs_pe: true,
}
opt: {
  learning_rate: 0.0001,
  epochs: 16,
  weight_decay: 0.05,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 250,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
#  label_smoothing: 0.1,
  dropout: 0.1,
  droppath: 0.1,
}
test_cfg: {
  pre_nms_topk: 5000,
  max_seg_num: 2000,
  min_score: 0.001,
  nms_sigma: 0.9,
  multiclass_nms: True,
  voting_thresh: 0.95,
}
output_folder: ./ckpt/
